In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Jateng' 30 40000]
 ['Jatim' 20 38000]
 ['Jabar' 26 36000]
 ['Kaltim' 29 50000]
 ['Sumsel' 40 44000]
 ['Sumsel' 38 22000]
 ['Kaltim' 51 35000]
 ['Jateng' 47 29000]
 ['Jabar' 23 52000]
 ['Jatim' 49 47000]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Jateng' 30.0 40000.0]
 ['Jatim' 20.0 38000.0]
 ['Jabar' 26.0 36000.0]
 ['Kaltim' 29.0 50000.0]
 ['Sumsel' 40.0 44000.0]
 ['Sumsel' 38.0 22000.0]
 ['Kaltim' 51.0 35000.0]
 ['Jateng' 47.0 29000.0]
 ['Jabar' 23.0 52000.0]
 ['Jatim' 49.0 47000.0]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 30.0 40000.0]
 [0.0 0.0 1.0 0.0 0.0 20.0 38000.0]
 [1.0 0.0 0.0 0.0 0.0 26.0 36000.0]
 [0.0 0.0 0.0 1.0 0.0 29.0 50000.0]
 [0.0 0.0 0.0 0.0 1.0 40.0 44000.0]
 [0.0 0.0 0.0 0.0 1.0 38.0 22000.0]
 [0.0 0.0 0.0 1.0 0.0 51.0 35000.0]
 [0.0 1.0 0.0 0.0 0.0 47.0 29000.0]
 [1.0 0.0 0.0 0.0 0.0 23.0 52000.0]
 [0.0 0.0 1.0 0.0 0.0 49.0 47000.0]]


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [15]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 51.0 35000.0]
 [0.0 0.0 0.0 0.0 1.0 40.0 44000.0]
 [0.0 1.0 0.0 0.0 0.0 30.0 40000.0]
 [0.0 0.0 0.0 1.0 0.0 29.0 50000.0]
 [0.0 0.0 1.0 0.0 0.0 20.0 38000.0]
 [0.0 1.0 0.0 0.0 0.0 47.0 29000.0]
 [1.0 0.0 0.0 0.0 0.0 23.0 52000.0]
 [0.0 0.0 0.0 0.0 1.0 38.0 22000.0]]


In [16]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 26.0 36000.0]
 [0.0 0.0 1.0 0.0 0.0 49.0 47000.0]]


In [17]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [18]:
print(y_test)

[0 1]


In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [21]:
print(x_train)

[[0.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 1.5641096225671218
  -0.39487359486949225]
 [0.0 0.0 0.0 -0.5773502691896258 1.7320508075688774 0.5053277242139932
  0.5528230328172892]
 [0.0 1.0 0.0 -0.5773502691896258 -0.5773502691896258
  -0.45720127428885105 0.1316245316231641]
 [0.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 -0.5534541741391354
  1.1846207846084769]
 [0.0 0.0 1.0 -0.5773502691896258 -0.5773502691896258 -1.4197302727916954
  -0.07897471897389845]
 [0.0 1.0 0.0 -0.5773502691896258 -0.5773502691896258 1.1790980231659842
  -1.0266713466606798]
 [1.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 -1.130971573240842
  1.3952200352055393]
 [0.0 0.0 0.0 -0.5773502691896258 1.7320508075688774 0.3128219245134244
  -1.7637687237503987]]


In [22]:
print(x_test)

[[1.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 -0.8422128736899888
  -0.289573969570961]
 [0.0 0.0 1.0 -0.5773502691896258 -0.5773502691896258 1.371603822866553
  0.868721908712883]]
